# Generated by Django 4.2.1 on 2023-06-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_words_remove_post_category_delete_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="words",
            name="collect",
            field=models.BooleanField(default=True),
        ),
    ]
