# Generated by Django 4.2.1 on 2023-06-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_rename_name_words_word_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct_count", models.IntegerField(default=0)),
                ("total_count", models.IntegerField(default=0)),
                ("response_times", models.JSONField(default=list)),
                ("last_answer_time", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="words",
        ),
        migrations.AddField(
            model_name="userword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dictionary.word"
            ),
        ),
    ]
